include:
  - ../wireguard/compose.yaml

services:
  qbittorent:
    container_name: qbittorrent
    image: docker.io/qbittorrentofficial/qbittorrent-nox:latest
    depends_on:
      wireguard:
        condition: service_healthy

    user: $PUID:$PGID
    read_only: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL

    network_mode: service:wireguard

    environment:
      TZ: $TZ
      QBT_LEGAL_NOTICE: confirm
      QBT_DOWNLOADS_PATH: /data/torrents

    # NOTE: traefik configuration is done in wireguard.

    tmpfs:
      - /tmp:noexec

    volumes:
      - ./state:/config/qBittorrent:rw
      - $DATA_DIR/torrents:/data/torrents:rw

    restart: unless-stopped
