include:
  - ../compose.common.yaml
  - ../traefik/compose.yaml

services:
  wireguard:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    healthcheck:
      test:
        - CMD-SHELL
        - "[ \"$(nslookup $DOMAIN | awk -F': ' 'NR==6 { print $$2 }')\" != \"$(curl --silent https://ifconfig.me)\" ]"
      interval: 5s
      timeout: 5s
      retries: 3

    # NOTE:
    # Root access is required for creating networking interfaces and modifying
    # routing rules. Read-only is not supported since client mode updates
    # resolvconf, etc.
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - CHOWN

    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ

    networks:
      - media
      - traefik

    expose:
      - &qbittorrent_port 8080
      - &slskd_port 5030

    labels:
      traefik.enable: true

      traefik.http.routers.qbittorrent.service: qbittorrent
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent.$DOMAIN`)
      traefik.http.routers.qbittorrent.entrypoints: websecure
      traefik.http.routers.qbittorrent.tls.certresolver: le
      traefik.http.services.qbittorrent.loadbalancer.server.port: *qbittorrent_port

      traefik.http.routers.slskd.service: slskd
      traefik.http.routers.slskd.rule: Host(`slskd.$DOMAIN`)
      traefik.http.routers.slskd.entrypoints: websecure
      traefik.http.routers.slskd.tls.certresolver: le
      traefik.http.services.slskd.loadbalancer.server.port: *slskd_port

    volumes:
      - ./state:/config:rw

    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

    restart: unless-stopped
