include:
  - ./services/actual/compose.yaml
  - ./services/audiobookshelf/compose.yaml
  - ./services/ddclient/compose.yaml
  - ./services/jellyfin/compose.yaml
  - ./services/microbin/compose.yaml
  - ./services/miniflux/compose.yaml
  - ./services/opodsync/compose.yaml
  - ./services/prowlarr/compose.yaml
  - ./services/qbittorrent/compose.yaml
  - ./services/readarr/compose.yaml
  - ./services/recyclarr/compose.yaml
  - ./services/slskd/compose.yaml
  - ./services/soju/compose.yaml
  - ./services/sonarr/compose.yaml
  - ./services/syncthing/compose.yaml
  - ./services/traefik/compose.yaml
  - ./services/uptime-kuma/compose.yaml
