# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

sonarr:
  anime-sonarr-v4:
    base_url: http://sonarr:8989
    api_key: !env_var SONARR_API_KEY

    include:
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime

    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    quality_profiles:
      # Do not reset language preference rules.
      - name: Remux-1080p - Anime
        reset_unmatched_scores:
          enabled: true
          except:
            - "Language: Prefer Japanese"
            - "Language: Prefer English"
            - "Language: Prefer Original"

    custom_formats:
      - trash_ids:
          - b2550eb333d27b75833e25b8c2557b38  # 10bit
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 10  # Prefer within the same tier

    media_naming:
      series: jellyfin
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default
